### ISSUE TITLE
Cannot build: can't find reason for requirement on github.com/google/pprof

### ISSUE THREAD

**Issue by anaisbetts** [tailscale/caddy-tailscale#11]
I wanted to give this a try because it looks extremely Cool, but I'm having trouble building it, it seems that the Go package manager is getting Confused:

```
go: downloading github.com/jackc/pgproto3/v2 v2.3.1
go: downloading github.com/go-logfmt/logfmt v0.5.1
go: downloading github.com/mgutz/ansi v0.0.0-20200706080929-d51e80ef957d
go: downloading github.com/AndreasBriese/bbloom v0.0.0-20190825152654-46b345b51c96
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/golang/glog v1.0.0
go: downloading github.com/jackc/chunkreader/v2 v2.0.1
go: downloading github.com/jackc/pgpassfile v1.0.0
go: downloading github.com/jackc/pgservicefile v0.0.0-20200714003250-2b9c44734f2b
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc000b26618, 0x17}, {0xc0000306f0, 0x22}})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:1760 +0xd4
cmd/go/internal/modget.(*resolver).updateBuildList(0xc000156000, {0xb3bd58, 0xc00002c0e0}, {0x0, 0x0, 0x0})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:1765 +0x54c
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc000156000, {0xb3bd58, 0xc00002c0e0}, {0x0?, 0x0, 0xc0000a5d70?})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:1312 +0x465
cmd/go/internal/modget.runGet({0xb3bd58, 0xc00002c0e0}, 0xc000028618?, {0xc000024220, 0x2, 0x2})
        /usr/lib/go/src/cmd/go/internal/modget/get.go:351 +0x458
main.invoke(0xe51280, {0xc0000241f0, 0x5, 0x5})
        /usr/lib/go/src/cmd/go/main.go:225 +0x3d9
main.main()
        /usr/lib/go/src/cmd/go/main.go:179 +0x7ce
2023/03/05 14:38:04 [FATAL] exit status 2
```

**Comment by mholt** [comment]
It is super cool!

But alas, you have hit a [known bug in the `go` command](https://github.com/golang/go/issues/56494).

We've figured out, that with Caddy, specifying the version of v2.6.3 or higher (v2.6.4 is current) fixes it. The plugin can do that in its go.mod or you can manually create a replacement in your own go.mod.

**Comment by Zaba** [comment]
I've had to update both the Caddy and the Tailscale dependencies to get this to build and to work (somehow with the old Tailscale version the node would seemingly be connected to the tailnet but no traffic would actually go through)

```patch
--- a/go.mod
+++ b/go.mod
@@ -3,8 +3,8 @@ module github.com/tailscale/caddy-tailscale
 go 1.19
 
 require (
-       github.com/caddyserver/caddy/v2 v2.5.3-0.20220831215348-67098e5cbd68
-       tailscale.com v1.1.1-0.20220902232949-3344c3b89bd1
+       github.com/caddyserver/caddy/v2 v2.6.4
+       tailscale.com v1.36.2
 )
 
 require (
```

(+ many more changes after running `go mod tidy`)

I've also had to patch the module slightly because the newer version of `tsnet` verifies the `network` parameter in `Listen`. I just hardcoded `"tcp"`, not sure if that's strictly correct but it seemed to work.

```patch
--- a/module.go
+++ b/module.go
@@ -46,7 +46,7 @@ func getPlainListener(_ context.Context, network string, addr string, _ net.List
                return nil, err
        }
 
-       return s.Listen(network, ":"+port)
+       return s.Listen("tcp", ":"+port)
 }
 
 func getTLSListener(_ context.Context, network string, addr string, _ net.ListenConfig) (any, error) {
@@ -60,7 +60,7 @@ func getTLSListener(_ context.Context, network string, addr string, _ net.Listen
                return nil, err
        }
 
-       ln, err := s.Listen(network, ":"+port)
+       ln, err := s.Listen("tcp", ":"+port)
        if err != nil {
                return nil, err
        }
```

**Comment by gbraad** [comment]
> specifying the version of v2.6.3 or higher (v2.6.4 is current) fixes it. 

As we also concluded in #9, this has to be proposes as a PR

**Comment by gbraad** [comment]
I applied to changes as originally I also ran into compiling issues with the old dependencies (ref: #9). I have a repo, that works with gitpod at: https://gitpod.io/#https://github.com/spotsnel/caddy-tailscale

the changes in `module.go` are needed, otherwise it fails to start with:
`Error: loading initial config: loading new config: http app module: start: listening on tailscale/caddy:80: unsupported network type`

Besides this, it works... any suggestions to remove the hard-coded `tcp` part?

**Comment by fr3nchalp4a** [comment]
Hey ! Running into same issue here !
Here are some logs, if they are some kind of useful :
```bash
2023/06/15 21:00:24 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go get -d -v
2023/06/15 21:00:28 [INFO] Build environment ready
2023/06/15 21:00:28 [INFO] Building Caddy
2023/06/15 21:00:28 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go mod tidy -e
go: finding module for package golang.org/x/crypto/internal/subtle
caddy imports
        github.com/tailscale/caddy-tailscale imports
        tailscale.com/tsnet imports
        tailscale.com/ipn/ipnlocal imports
        github.com/tailscale/golang-x-crypto/ssh imports
        github.com/tailscale/golang-x-crypto/chacha20 imports
        github.com/tailscale/golang-x-crypto/internal/subtle tested by
        github.com/tailscale/golang-x-crypto/internal/subtle.test imports
        golang.org/x/crypto/internal/subtle: module golang.org/x/crypto@latest found (v0.10.0), but does not contain package golang.org/x/crypto/internal/subtle
2023/06/15 21:00:28 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go build -o /home/pi/temp/caddy -ldflags -w -s -trimpath
package caddy
        imports github.com/tailscale/caddy-tailscale
        imports tailscale.com/tsnet
        imports tailscale.com/ipn/ipnlocal
        imports tailscale.com/net/dns
        imports tailscale.com/net/tstun
        imports gvisor.dev/gvisor/pkg/tcpip
        imports gvisor.dev/gvisor/pkg/atomicbitops
        imports gvisor.dev/gvisor/pkg/cpuid
        imports gvisor.dev/gvisor/pkg/state
        imports gvisor.dev/gvisor/pkg/state/wire
        imports gvisor.dev/gvisor/pkg/gohacks: build constraints exclude all Go files in /home/pi/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20220801230058-850e42eb4444/pkg/gohacks
2023/06/15 21:00:29 [INFO] Cleaning up temporary folder: /tmp/buildenv_2023-06-15-2100.2723375457
2023/06/15 21:00:29 [FATAL] exit status 1
```
```bash
pi@john:~/temp $ go version
go version go1.20.5 linux/arm64
```
I'm on Raspberry Pi 4GB, running latest Go and xcaddy, Raspberry Pi OS based on Debian 11.

**Comment by fr3nchalp4a** [comment]
Oh, I didn't realised it wasn't the same issue

**Comment by vamega** [comment]
@fr3nchalp4a I ran into that issue as well.
Manually patched the value in go.mod to use the value from https://github.com/tailscale/tailscale/pull/6168/

I'm still running into some issues, but am getting closer.

```
caddy imports
        github.com/tailscale/caddy-tailscale imports
        tailscale.com/util/strs: cannot find module providing package tailscale.com/util/strs
caddy imports
        github.com/caddyserver/caddy/v2/modules/standard imports
        github.com/caddyserver/caddy/v2/modules/caddypki/acmeserver imports
        github.com/smallstep/certificates/acme imports
        github.com/smallstep/go-attestation/attest imports
        github.com/google/go-tpm/tpm2/credactivation: cannot find module providing package github.com/google/go-tpm/tpm2/credactivation
        ```
        
The first error is due to this [commit](https://github.com/tailscale/tailscale/commit/b1248442c3e40371c34fdf5bd90138b3ece615a7).

I'm going to need to learn some go to tackle this, it seems like mashing commands I don't understand isn't going to get me to power through the dependency hell that my chosen set of plugins seems to create.

`xcaddy` does panic with the exception that started this thread.

```
> xcaddy version
v0.3.4

> xcaddy build --with github.com/tailscale/caddy-tailscale --with github.com/caddyserver/caddy/v2/modules/standard --with github.com/caddy-dns/cloudflare --with github.com/lum8rjack/caddy-maxmind-geolocation

[ Snipped ]go: downloading github.com/jackc/pgproto3/v2 v2.3.1
go: downloading github.com/golang/glog v1.0.0
panic: internal error: can't find reason for requirement on github.com/google/pprof@v0.0.0-20210407192527-94a9f03dee38

goroutine 1 [running]:
cmd/go/internal/modget.(*resolver).updateBuildList.func1({{0xc001605e90, 0x17}, {0xc000034660, 0x22}})
        /nix/store/i3ab37h47xmd0zh75708gj57hah7v7f4-go-1.20.5/share/go/src/cmd/go/internal/modget/get.go:1760 +0xd4
cmd/go/internal/modget.(*resolver).updateBuildList(0xc00013e000, {0xb45e38, 0xc000032240}, {0x0, 0x0, 0x0})
        /nix/store/i3ab37h47xmd0zh75708gj57hah7v7f4-go-1.20.5/share/go/src/cmd/go/internal/modget/get.go:1765 +0x54c
cmd/go/internal/modget.(*resolver).applyUpgrades(0xc00013e000, {0xb45e38, 0xc000032240}, {0x0?, 0x0, 0xc0000bfd70?})
        /nix/store/i3ab37h47xmd0zh75708gj57hah7v7f4-go-1.20.5/share/go/src/cmd/go/internal/modget/get.go:1312 +0x465
cmd/go/internal/modget.runGet({0xb45e38, 0xc000032240}, 0xc00002e660?, {0xc000024220, 0x2, 0x2})
        /nix/store/i3ab37h47xmd0zh75708gj57hah7v7f4-go-1.20.5/share/go/src/cmd/go/internal/modget/get.go:351 +0x458
main.invoke(0xe67340, {0xc0000241f0, 0x5, 0x5})
        /nix/store/i3ab37h47xmd0zh75708gj57hah7v7f4-go-1.20.5/share/go/src/cmd/go/main.go:225 +0x3d9
main.main()
        /nix/store/i3ab37h47xmd0zh75708gj57hah7v7f4-go-1.20.5/share/go/src/cmd/go/main.go:179 +0x7ce
2023/07/14 19:53:48 [FATAL] exit status 2
```

**Comment by vamega** [comment]
I was able to get this to build by replacing the the tailscale-caddy module with the contents on https://github.com/tailscale/caddy-tailscale/pull/13/.

```
 go mod edit --replace github.com/tailscale/caddy-tailscale=github.com/trea/caddy-tailscale@network-listener-changes
 ```

**Comment by icb-** [comment]
> I was able to get this to build by replacing the the tailscale-caddy module with the contents on #13.
> 
> ```
>  go mod edit --replace github.com/tailscale/caddy-tailscale=github.com/trea/caddy-tailscale@network-listener-changes
> ```

Caddy introduced [a breaking change](https://github.com/caddyserver/caddy/commit/e16a886814d8cd43d545de38a4d6b98313fb31cb) so `caddytls.AutomationPolicy` field `Subjects` needs to be `SubjectsRaw` at [`command.go` line 202](https://github.com/trea/caddy-tailscale/blob/network-listener-changes/command.go#L202) to build against Caddy `master`. After fixing that, you should be able to build with `xcaddy build master --with github.com/tailscale/caddy-tailscale=github.com/trea/caddy-tailscale@network-listener-changes`.

**Comment by willnorris** [comment]
#13 has been merged, which I believe addresses most (or all?) of the issues mentioned here.  This bumps us to caddy v2.6.4, which @mholt noted fixes the original problem discussed.  #13 also includes some other changes which I believe takes care of needing to hardcard a network value of "tcp" as well as the tailscale.com/util/strs issue.  

If any of these problems remain after updating to the latest version of caddy-tailscale, feel free to reply here or open a new issue.

**Comment by mholt** [comment]
Yayyyy thanks Will!
